#!/bin/zsh
set -euo pipefail

SCRIPT_DIR=${0:A:h}
SERVICE_DIR=${SCRIPT_DIR:h:h}
REPO_ROOT=${SERVICE_DIR:h:h}
RUNTIME_DIR=${REPO_ROOT}/.runtime/docling-release/macos
VENV_DIR=${RUNTIME_DIR}/venv

export DOCLING_RELEASE_PROFILE=macos
export DOCLING_SERVE_URL=http://127.0.0.1:${DOCLING_BACKEND_PORT:-5001}
export DOCLING_INPUT_ROOT=${RUNTIME_DIR}/data/inputs
export DOCLING_OUTPUT_ROOT=${RUNTIME_DIR}/data/outputs
export DOCLING_STATE_ROOT=${RUNTIME_DIR}/data/state
mkdir -p ${DOCLING_STATE_ROOT}/temp
export TMPDIR=${DOCLING_STATE_ROOT}/temp
export DOCLING_API_HOST=${DOCLING_API_HOST:-127.0.0.1}
export DOCLING_API_PORT=${DOCLING_API_PORT:-8000}
export DOCLING_MAX_CONCURRENT_JOBS=${DOCLING_MAX_CONCURRENT_JOBS:-1}
export DOCLING_MAX_CONCURRENT_UPLOADS=${DOCLING_MAX_CONCURRENT_UPLOADS:-2}
export DOCLING_IMAGE_EXPORT_MODE=${DOCLING_IMAGE_EXPORT_MODE:-embedded}

exec ${VENV_DIR}/bin/docling-service-api
