#!/bin/zsh
set -euo pipefail

SCRIPT_DIR=${0:A:h}
SERVICE_DIR=${SCRIPT_DIR:h:h}
REPO_ROOT=${SERVICE_DIR:h:h}
RUNTIME_DIR=${REPO_ROOT}/.runtime/docling-release/macos
VENV_DIR=${RUNTIME_DIR}/venv

export UVICORN_WORKERS=1
export DOCLING_DEVICE=${DOCLING_DEVICE:-cpu}
export HF_HUB_DISABLE_XET=${HF_HUB_DISABLE_XET:-1}
export HF_HUB_DOWNLOAD_TIMEOUT=${HF_HUB_DOWNLOAD_TIMEOUT:-600}
export DOCLING_INFERENCE_COMPILE_TORCH_MODELS=${DOCLING_INFERENCE_COMPILE_TORCH_MODELS:-false}
export DOCLING_SERVE_ALLOW_CUSTOM_CODE_FORMULA_CONFIG=true
export DOCLING_SERVE_ALLOW_CUSTOM_OCR_CONFIG=true
export DOCLING_SERVE_ALLOWED_CODE_FORMULA_PRESETS=${DOCLING_SERVE_ALLOWED_CODE_FORMULA_PRESETS:-default,granite_docling}
export DOCLING_SERVE_ENG_KIND=local
export DOCLING_SERVE_ENG_LOC_NUM_WORKERS=1
export DOCLING_SERVE_ENG_LOC_SHARE_MODELS=true
export DOCLING_SERVE_ARTIFACTS_PATH=${DOCLING_MODEL_CACHE:-${HOME}/.cache/docling/models}
export DOCLING_SERVE_LOAD_MODELS_AT_BOOT=${DOCLING_SERVE_LOAD_MODELS_AT_BOOT:-true}
export DOCLING_SERVE_OPTIONS_CACHE_SIZE=2
export DOCLING_SERVE_MAX_SYNC_WAIT=${DOCLING_CONVERSION_TIMEOUT_SECONDS:-3600}

exec ${VENV_DIR}/bin/docling-serve run \
  --host 127.0.0.1 \
  --port ${DOCLING_BACKEND_PORT:-5001} \
  --artifacts-path ${DOCLING_SERVE_ARTIFACTS_PATH}
